language: php
php:
 - 7.3.5

before_script:
 - composeur install 
 - php bin/console doctrine:migrations:diff
 - php bin/console doctrine:migrations:migrate
 - php bin/console doctrine:fixtures:load

env:
- DATABASE_URL=pgsql://slamquiz:admin@127.0.0.1:5432/slamquiz