language: php
php:
  - 7.3.5
services:
  - postgresql
env:
  - DATABASE_URL=pgsql://slamquiz:admin@127.0.0.1:5432/slamquiz
before_script:
  - psql -c "CREATE USER slamquiz WITH PASSWORD 'admin';" -U postgres
  - psql -c "CREATE DATABASE slamquiz;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE slamquiz TO slamquiz;" -U postgres
script:
 - composer install 
 - php bin/console doctrine:schema:update --force
 - php bin/console doctrine:fixtures:load -n
 - php bin/phpunit
